Name: Yuvraj Pavan Sabale
Batch: AIML
Day: 7(16th August 2026)
Assignment: Day 7(offline)
Description: This assignment focuses on external libraries like numpy and as well get and post requests and how we can access them through urllib or an external requests library.

In [ ]:
import math

math.sqrt(25)


5.0

In [ ]:
def root(num):
  root_of_num = num ** 0.5
  return root_of_num

print(root(25))



5.0


you need libraries for:-

-math & calculations
-files
-websites and internet
-graphs and charts
-data processing
-dates and time
-databases
-machine learning models

In [ ]:
pip install numpy

In [ ]:
nums = [1,2,3,4,5] #python list we have to perform any operation on each individul element in the list

print(nums)

[1, 2, 3, 4, 5]


In [ ]:
import numpy as np

#numpy array we can perform any operation on the whole array at once
numbers = np.array(
    [10,20,30,40]
)

print(numbers)

[10 20 30 40]


In [ ]:
numbers = [10,20,30,40]

result =[]

for n in numbers:
  result.append(n*2)

print(result)

[20, 40, 60, 80]


In [ ]:
import numpy as np

numbers = np.array(
    [10,20,30,40]
)

result = numbers * 2

print(result)

[20 40 60 80]


In [2]:
import numpy as np

print(np.zeros(5)) #array of 5 zeroes
print(np.ones(5)) #array of 5 ones
print(np.arange(0,10,2)) # it will create an array starting from 0 to < 10 and increment by 2

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[0 2 4 6 8]


In [ ]:
numbers = np.array([10,20,30])

print(numbers[0])
numbers[1] = 99
print(numbers)

10
[10 99 30]


In [ ]:
numbers = [10,20,30]
numbers[1] = 99
print(numbers)

[10, 99, 30]


In [ ]:
#it performs operations on all the elements at once instead of individually

numbers = np.array([10,20,30])
print(numbers + 5)
print(numbers * 5)
print(numbers / 5)

[15 25 35]
[ 50 100 150]
[2. 4. 6.]


In [ ]:
#performs arithmetic operations between two arrays

a = np.array([10,20,30])
b = np.array([5,10,15])

print(a + b)
print(a * b)

[15 30 45]
[ 50 200 450]


In [ ]:
#inbuilt functions in numpy

numbers = np.array([10,20,30])

print(np.sum(numbers))
print(np.mean(numbers)) #arithmetic mean
print(np.max(numbers))

60
20.0
30


In [ ]:
numbers = np.array([[10,20,50],[10,20,30]])
print(numbers.shape)
print(numbers[1,2])

(2, 3)
30


In [ ]:
import urllib.request #built-in module to access an website
response = urllib.request.urlopen('https://goslings.online')
print(response.status)

200


In [ ]:
#instead we will use the third part 'requests' library for simpler syntax


In [ ]:
pip install requests

In [ ]:
import requests

response = requests.get("https://goslings.online")
print(response.status_code)
print(response.text)
print(response.raise_for_status)





200
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Yuvraj Sabale — Full Stack Developer</title>
    <meta name="description" content="Yuvraj Sabale is a Full Stack Developer and Computer Engineering student specializing in JavaScript, React.js, and scalable web applications." />
    <meta name="keywords" content="Yuvraj Sabale, Full Stack Developer, React, JavaScript, Node.js, Portfolio" />
    <meta property="og:title" content="Yuvraj Sabale — Full Stack Developer" />
    <meta property="og:description" content="Building scalable modern web applications with JavaScript and the MERN stack." />
    <meta property="og:type" content="website" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.g

req.post(url, json=data),
req.get(url
)